---
driver:
  name: "terraform"
  command_timeout: 1800

provisioner:
  name: "terraform"

platforms:
  - name: local

suites:
  - name: "simple_vpc"
    driver:
      name: "terraform"
      command_timeout: 1800
      root_module_directory: test/fixtures/simple_vpc/
    verifier:
      name: terraform
      color: true
      systems:
        - name: inspec-gcp
          backend: gcp
          controls:
            - gcp
        - name: local
          backend: local
          controls:
            - gcloud
  - name: "vpc_secondary_ranges"
    driver:
      name: "terraform"
      command_timeout: 1800
      root_module_directory: test/fixtures/vpc_secondary_ranges/
    verifier:
      name: terraform
      color: true
      systems:
        - name: local
          backend: local
          controls:
            - gcloud
  - name: "vpc_autosubnets"
    driver:
      name: "terraform"
      command_timeout: 1800
      root_module_directory: test/fixtures/vpc_autosubnets/
    verifier:
      name: terraform
      color: true
      systems:
        - name: inspec-gcp
          backend: gcp
          controls:
            - gcp
        - name: local
          backend: local
          controls:
            - gcloud
  - name: "multi_vpc"
    driver:
      name: "terraform"
      command_timeout: 1800
      root_module_directory: test/fixtures/multi_vpc/
    verifier:
      name: terraform
      color: true
      systems:
        - name: local
          backend: local
          controls:
            - gcloud
  - name: "submodule_firewall"
    driver:
      name: "terraform"
      command_timeout: 1800
      root_module_directory: test/fixtures/submodule_firewall/
    verifier:
      name: terraform
      color: true
      systems:
        - name: inspec-gcp
          backend: gcp
          controls:
            - gcp
        - name: local
          backend: local
          controls:
            - gcloud
  - name: "simple_vpc_with_regional_network"
    driver:
      name: "terraform"
      command_timeout: 1800
      root_module_directory: test/fixtures/simple_vpc_with_regional_network/
    verifier:
      name: terraform
      color: true
      systems:
        - name: inspec-gcp
          backend: gcp
          controls:
            - gcp
