---
driver:
  name: "terraform"
  command_timeout: 1800

provisioner:
  name: "terraform"

platforms:
  - name: local

suites:
  - name: "simple_vpc"
    driver:
      name: "terraform"
      command_timeout: 1800
      root_module_directory: test/fixtures/simple_vpc/
    verifier:
      name: terraform
      color: true
      systems:
        - name: inspec-gcp
          backend: gcp
          controls:
            - gcp
        - name: local
          backend: local
          controls:
            - gcloud
  - name: "secondary_ranges"
    driver:
      name: "terraform"
      command_timeout: 1800
      root_module_directory: test/fixtures/secondary_ranges/
    verifier:
      name: terraform
      color: true
      systems:
        - name: local
          backend: local
          controls:
            - gcloud
