env: &docker    
  docker:
    - image: leandevopsio/buildenv:0.1

version: 2
jobs:
  check_terraform:
    <<: *docker
    steps:
      - checkout
      - run:
          name: Run terraform init validate fmt
          command: make check_terraform
      - run:
          name: Run tflint
          command: tflint
      - run:
          name: Run check_shell
          command: make check_shell

  run-tests:
    <<: *docker
    environment:
      BUNDLE_PATH: vendor

    steps:
      - checkout
      - restore_cache:
          keys:
            - terraform-gcp-vpc-{{ checksum "Gemfile.lock" }}
            - terraform-gcp-vpc-
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: terraform-gcp-vpc-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor
      - run:
          name: Run test command
          command: echo ${CIRCLE_PROJECT_REPONAME}
      
workflows:
  version: 2
  tf-workflow:
    jobs:      
      - check_terraform
      # - request-run:
      #     type: approval
      #     requires:
      #       - terraform-validate
      #       - terraform-fmt
      #       - tflint
      #     filters:
      #       branches:
      #         ignore: master
      - run-tests:
          requires:
            - check_terraform
      #     filters:
      #       branches:
      #         ignore: master