env: &docker    
  docker:
    - image: leandevopsio/terratest:0.3

version: 2
jobs:
  check_terraform:
    <<: *docker
    steps:
      - checkout      
      - run:
          name: terraform init validate fmt
          command: make check_terraform
      - run:
          name: Check Terraform configurations with tflint
          command: tflint
  # run-tests:
  #   <<: *docker
  #   environment:
  #     BUNDLE_PATH: vendor

  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #           - tf-gcp-network-{{ checksum "Gemfile.lock" }}

  #     - run:
  #         name: Bundle Install
  #         command: bundle check || bundle install
      
  #     - save_cache:
  #         key: tf-gcp-network-{{ checksum "Gemfile.lock" }}
  #         paths:
  #           - vendor

  #     - run:
  #         name: Run make to zip a function code
  #         command: make build

  #     - run:
  #         name: Run rspec test
  #         command: make

workflows:
  version: 2
  tf-workflow:
    jobs:      
      - check_terraform
      # - check_tflint:
      #     requires:
      #       - check_terraform
      # - request-run:
      #     type: approval
      #     requires:
      #       - terraform-validate
      #       - terraform-fmt
      #       - tflint
      #     filters:
      #       branches:
      #         ignore: master
      # - run-tests:
      #     requires:
      #       - request-run
      #     filters:
      #       branches:
      #         ignore: master